#!/usr/bin/env php

<?php

require_once __DIR__ . "/vendor/autoload.php";

use Woodlands\Core\Database\Connection;

const MODELS_DIRECTORY = __DIR__."/src/Models";

function get_tables()
{
    $conn = Connection::getInstance()->getConnection();
    $tables = $conn->query("SHOW TABLES")->fetchAll(PDO::FETCH_COLUMN);
    return $tables;
}

function get_columns_metadata(string $table)
{
    $conn = Connection::getInstance()->getConnection();
    $stmt = $conn->prepare("DESCRIBE $table");
    $stmt->execute();
    $columns = $stmt->fetchAll(PDO::FETCH_ASSOC);
    return $columns;
}

function get_column_type(string $column)
{
    $type = match(true) {
        str_contains($column, "int") => "int",
        str_contains($column, "tinyint") => "bool",
        str_contains($column, "varchar"), str_contains($column, "text") => "string",
        str_contains($column, "datetime"), str_contains($column, "timestamp") => "DateTime",
        default => "mixed",
    };
    return $type;
}

function main()
{
    $dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
    $dotenv->safeLoad();

    $tables = get_tables();
    foreach($tables as $table) {
        if($table === "__migrations" || $table === "users") {
            continue;
        }

        $columns_meta = get_columns_metadata($table);
        $model_name = str_replace("_", "", ucwords($table, "_"));
        $model_name = str_ends_with($model_name, "s") ? substr($model_name, 0, -1) : $model_name;

        echo $model_name.PHP_EOL;
    }
}

main();
